apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: ai-webui
spec:
  type: ClusterIP
  selector:
    app: ai-webui-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
