apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: ai-webui
spec:
  type: ClusterIP
  selector:
    app: ai-webui-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
